version: "3.8"

services:
    api_gateway:
        build: ./api_gateway
        ports:
            - "8000:8000"
        depends_on:
            - notification_service

    notification_service:
        build: ./notification_service
        ports:
            - "8001:8001"
        depends_on:
            - rabbitmq
            - cassandra # Add dependency on Cassandra

    rabbitmq:
        image: "rabbitmq:3-management"
        container_name: "rabbitmq"
        ports:
            - "5672:5672"
            - "15672:15672"

    cassandra:
        image: "cassandra:latest"
        container_name: "cassandra_db"
        ports:
            - "9042:9042"
        environment:
            - CASSANDRA_START_RPC=true

    postgres_db:
        image: "postgres:latest"
        container_name: "notifications_db"
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - .env # Loads environment variables from .env

volumes:
    postgres_data:
