version: "3.8"

services:
    api_gateway:
        build: ./api_gateway
        ports:
            - "8000:8000"
        depends_on:
            - notification_service

    notification_service:
        build: ./notification_service
        ports:
            - "8001:8001"
        depends_on:
            - rabbitmq

    rabbitmq:
        image: "rabbitmq:3-management"
        container_name: "rabbitmq"
        ports:
            - "5672:5672"
            - "15672:15672"
